### PR TITLE
Low-lying fruit

### PR DESCRIPTION
**Pull request by EdNoepel**
# Description of change
## High level
Resolved some low-severity issues brought up in Kirill and Sherlock audits.  Added some unit tests to disprove issues brought up in Sherlock audit.

# Description of bug or vulnerability and solution
**Kirill L-05** - Removed redundant parameters and logic from `_lpToQuoteToken` method (https://github.com/k1rill-fedoseev/audits/blob/master/solo/Ajna.md)
**Kirill L-07** - Added comment explaining `getDeployedPoolsList` method is not for onchain use (https://github.com/k1rill-fedoseev/audits/blob/master/solo/Ajna.md)
**Sherlock [007-M](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/46)** - Added `SafeCast`s where appropriate to revert upon overflow.
**Sherlock [54](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/54) and [60](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/60)** - Added unit tests to prove invalid, including implementing test harness for auction queue.

# Contract size
Small increase in contract size from including `SafeCast` in `Pool` baseclass and `TakerActions` library.
## Pre Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,069B  (97.93%)
  ERC20Pool                -  23,360B  (95.05%)
  PositionManager          -  17,885B  (72.77%)
  TakerActions             -  15,866B  (64.56%)
```
## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,323B  (98.97%)
  ERC20Pool                -  23,614B  (96.08%)
  PositionManager          -  17,882B  (72.76%)
  TakerActions             -  16,001B  (65.11%)
```

# Gas usage
`SafeCast` induced a small gas penalty in interest-accruing transactions.
## Pre Change
| src/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                        | min             | avg    | median | max    | # calls |
| addCollateral                        | 1553            | 162395 | 144126 | 400771 | 34      |
| addQuoteToken                        | 1950            | 257429 | 171180 | 723088 | 903     |
| bucketTake                           | 8165            | 111714 | 107028 | 357178 | 34      |
| drawDebt                             | 7442            | 244655 | 230546 | 592550 | 521     |
| kick                                 | 6878            | 470667 | 572805 | 713526 | 56      |
| kickReserveAuction                   | 4090            | 43454  | 51755  | 100698 | 137     |
| kickerInfo                           | 1304            | 2332   | 1304   | 5304   | 140     |
| moveQuoteToken                       | 1918            | 141585 | 107168 | 634633 | 41      |
| removeCollateral                     | 4412            | 57127  | 58408  | 157370 | 103     |
| removeQuoteToken                     | 4698            | 70563  | 64360  | 621261 | 391     |
| repayDebt                            | 9853            | 194590 | 128398 | 589911 | 311     |
| settle                               | 11765           | 203393 | 170589 | 507761 | 60      |
| take                                 | 9159            | 185238 | 184787 | 579429 | 42      |
| takeReserves                         | 6714            | 104616 | 115461 | 153184 | 76      |

| src/ERC721Pool.sol:ERC721Pool contract |                 |        |        |          |         |
|----------------------------------------|-----------------|--------|--------|----------|---------|
| Function Name                          | min             | avg    | median | max      | # calls |
| addCollateral                          | 23601           | 268358 | 303067 | 738259   | 9       |
| addQuoteToken                          | 43467           | 279826 | 215624 | 682428   | 185     |
| bucketTake                             | 98327           | 193479 | 136773 | 508779   | 13      |
| drawDebt                               | 12207           | 362950 | 302620 | 11484930 | 166     |
| kick                                   | 6878            | 517649 | 565965 | 783665   | 13      |
| kickReserveAuction                     | 6912            | 57451  | 64977  | 104077   | 8       |
| kickerInfo                             | 1326            | 2468   | 1326   | 5326     | 42      |
| moveQuoteToken                         | 45953           | 53109  | 46131  | 67228    | 6       |
| removeCollateral                       | 3779            | 72163  | 66745  | 167878   | 21      |
| removeQuoteToken                       | 4830            | 62755  | 59002  | 182722   | 142     |
| repayDebt                              | 8354            | 243817 | 117597 | 7476997  | 118     |
| settle                                 | 108920          | 332643 | 268003 | 714682   | 15      |
| take                                   | 12144           | 311693 | 382145 | 706382   | 13      |
| takeReserves                           | 4449            | 82426  | 63969  | 164783   | 8       |

## Post Change
| src/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                        | min             | avg    | median | max    | # calls |
| addCollateral                        | 1553            | 162836 | 144673 | 401305 | 34      |
| addQuoteToken                        | 1950            | 254785 | 170564 | 723622 | 928     |
| bucketTake                           | 8165            | 113071 | 107028 | 398194 | 34      |
| drawDebt                             | 7442            | 244631 | 230546 | 592550 | 509     |
| kick                                 | 6878            | 511407 | 573339 | 714060 | 50      |
| kickReserveAuction                   | 4090            | 44945  | 51755  | 100698 | 125     |
| kickerInfo                           | 1304            | 2332   | 1304   | 5304   | 140     |
| moveQuoteToken                       | 1918            | 141744 | 107168 | 635167 | 41      |
| removeCollateral                     | 4412            | 57244  | 58955  | 157904 | 103     |
| removeQuoteToken                     | 4698            | 70866  | 64324  | 621795 | 397     |
| repayDebt                            | 9853            | 194232 | 127384 | 590445 | 305     |
| settle                               | 11765           | 214023 | 199993 | 437278 | 54      |
| take                                 | 9159            | 184991 | 185391 | 579097 | 42      |
| takeReserves                         | 6714            | 107588 | 140256 | 153184 | 70      |

| src/ERC721Pool.sol:ERC721Pool contract |                 |        |        |        |         |
|----------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                          | min             | avg    | median | max    | # calls |
| addCollateral                          | 23601           | 251198 | 303614 | 738793 | 9       |
| addQuoteToken                          | 43467           | 280581 | 216171 | 682962 | 184     |
| bucketTake                             | 98327           | 193601 | 136846 | 509313 | 13      |
| drawDebt                               | 12207           | 297778 | 302620 | 685792 | 166     |
| kick                                   | 6878            | 518068 | 566499 | 784199 | 13      |
| kickReserveAuction                     | 6912            | 57451  | 64977  | 104077 | 8       |
| kickerInfo                             | 1326            | 2468   | 1326   | 5326   | 42      |
| moveQuoteToken                         | 45953           | 53255  | 46131  | 67666  | 6       |
| removeCollateral                       | 3779            | 71534  | 66745  | 168305 | 21      |
| removeQuoteToken                       | 4830            | 63237  | 59519  | 183256 | 141     |
| repayDebt                              | 8354            | 185133 | 117597 | 643012 | 118     |
| settle                                 | 108920          | 333008 | 268537 | 715216 | 15      |
| take                                   | 12144           | 312014 | 382752 | 706986 | 13      |
| takeReserves                           | 4449            | 82426  | 63969  | 164783 | 8       |

### CODE REVIEW

**Review by ith-harvey — COMMENTED** [review]
Instead of saying that this PR addresses issues brought up in audits... what do you think about outlining the issue and then buleting out how these changes solves said issue?

**Review by prat-gpt — APPROVED** [review]
lgtm

**Comment by EdNoepel** [comment]
> Instead of saying that this PR addresses issues brought up in audits... what do you think about outlining the issue and then buleting out how these changes solves said issue?

Updated description with more detail and links to audit reports (where available).

**Review by ith-harvey — APPROVED** [review]
LGTM

**Review by mattcushman — APPROVED** [review]
lgtm.  Note however that there is some discussion involving whether the safecasts are necessary.  only harm is gas/size however.

**Review by dmitriia — COMMENTED** [review]
Looks ok

**Pull request merged**
