### PR TITLE
Eliminated IFenwickTree interface, updated IScaledPool to expose data

### PR DESCRIPTION
**Pull request by EdNoepel**
I left most of the externals in `FenwickTree` purely for the `FenwickTreeTest` contract, which does not create a pool.
Should these be moved into the `FenwickTreeInstance` derived test class instead?  Repointed all other tests to the appropriate pool method.  Repointed `ScaledPool` directly at internal methods.

| Old IFenwickTree name | IScaledPool name |
| ------------------------------- | ------------------------- |
| SIZE()                           | bucketCount()         |
| get()                              | depositAt()              |
| prefixSum()                  | liquidityToPrice()      |
| treeSum()                    | poolSize()                 |

### CODE REVIEW

**Review by grandizzy — APPROVED** [review]
LGTM. We can leave the other external functions and move them to tree instance if ERC721 pool size still exceeds the deployable limit (last time I checked it was)

**Comment by grandizzy** [comment]
> LGTM. We can leave the other external functions and move them to tree instance if ERC721 pool size still exceeds the deployable limit (last time I checked it was)

Just rechecked and that's the case, more `addCollateral` and `removeCollateral` are not even implemented yet in `ERC721Pool`. If not a biggie let's move those externals in `FenwickTreeInstance`

**Comment by EdNoepel** [comment]
> > LGTM. We can leave the other external functions and move them to tree instance if ERC721 pool size still exceeds the deployable limit (last time I checked it was)
> 
> Just rechecked and that's the case, more `addCollateral` and `removeCollateral` are not even implemented yet in `ERC721Pool`. If not a biggie let's move those externals in `FenwickTreeInstance`

👍 Done in c05aab061fd373a0299feeb453001c0414589e66.

**Comment by grandizzy** [comment]
> > > LGTM. We can leave the other external functions and move them to tree instance if ERC721 pool size still exceeds the deployable limit (last time I checked it was)
> > 
> > 
> > Just rechecked and that's the case, more `addCollateral` and `removeCollateral` are not even implemented yet in `ERC721Pool`. If not a biggie let's move those externals in `FenwickTreeInstance`
> 
> +1 Done in [c05aab0](https://github.com/ajna-finance/contracts/commit/c05aab061fd373a0299feeb453001c0414589e66).

Thank you!

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
