### PR TITLE
Created bucket instance to test Buckets library

### PR DESCRIPTION
**Pull request by ith-harvey**
## Description

* Added a testing instance for `Buckets.sol`
* Excluded tests for Bucket methods `lpToCollateral`, `lpToQuoteTokens` and `getExchangeRate` as they are tested in poolInfoUtils.
  * `lpToCollateral`: https://github.com/ajna-finance/contracts/blob/99c89e74023c8ef7b3adf58ed19cb2f3e3914cdf/tests/forge/unit/ERC20Pool/ERC20PoolInfoUtils.t.sol#L323-L324
  * `lpToQuoteTokens`: https://github.com/ajna-finance/contracts/blob/99c89e74023c8ef7b3adf58ed19cb2f3e3914cdf/tests/forge/unit/ERC20Pool/ERC20PoolInfoUtils.t.sol#L323-L324
  * `getExchangeRate`: https://github.com/ajna-finance/contracts/blob/99c89e74023c8ef7b3adf58ed19cb2f3e3914cdf/tests/forge/unit/ERC20Pool/ERC20PoolInfoUtils.t.sol#L208

## Purpose
* This code was not tested, now it is.

## Impact

* Just updated tests no impact to protocol

## Tasks

- [ ] Changes to protocol contracts are covered by unit tests executed by CI.
- [ ] Protocol contract size limits have not been exceeded.
- [ ] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [ ] Invariant tests have been manually executed as appropriate for the nature of the change.

### CODE REVIEW

**Review by prat-gpt — COMMENTED** [review]
three methods `lpToCollateral`, `lpToQuoteTokens` and `getExchangeRate` from `Buckets` library not yet covered.

**Comment by ith-harvey** [comment]
> three methods `lpToCollateral`, `lpToQuoteTokens` and `getExchangeRate` from `Buckets` library not yet covered.

* Excluded tests for Bucket methods `lpToCollateral`, `lpToQuoteTokens` and `getExchangeRate` as they are tested in poolInfoUtils.
  * `lpToCollateral`: https://github.com/ajna-finance/contracts/blob/99c89e74023c8ef7b3adf58ed19cb2f3e3914cdf/tests/forge/unit/ERC20Pool/ERC20PoolInfoUtils.t.sol#L323-L324
  * `lpToQuoteTokens`: https://github.com/ajna-finance/contracts/blob/99c89e74023c8ef7b3adf58ed19cb2f3e3914cdf/tests/forge/unit/ERC20Pool/ERC20PoolInfoUtils.t.sol#L323-L324
  * `getExchangeRate`: https://github.com/ajna-finance/contracts/blob/99c89e74023c8ef7b3adf58ed19cb2f3e3914cdf/tests/forge/unit/ERC20Pool/ERC20PoolInfoUtils.t.sol#L208
  
  Should have clarified this in the description... added it there.

**Review by prat-gpt — APPROVED** [review]
LGTM

**Review by EdNoepel — APPROVED** [review]
LGTM

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
