### PR TITLE
Add slither to analyze base, erc20 and erc721 contracts. Do not fail …

### PR DESCRIPTION
**Pull request by grandizzy**
…CI for now

### CODE REVIEW

**Review by EdNoepel — APPROVED** [review]
Is there a way to explicitly run the analysis?  Would be nice to have an action in `Makefile`.

**Comment by grandizzy** [comment]
> Is there a way to explicitly run the analysis? Would be nice to have an action in `Makefile`.

Yep, I'll add `Makefile` target and `Readme` section on how to install and run

**Comment by grandizzy** [comment]
> > Is there a way to explicitly run the analysis? Would be nice to have an action in `Makefile`.
> 
> Yep, I'll add `Makefile` target and `Readme` section on how to install and run

@EdNoepel added in https://github.com/ajna-finance/contracts/pull/203/commits/aae0d0011cf0175b4fdbe8e2b8a0acdc98697d4e

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
