### PR TITLE
Invariant framework improvements

### PR DESCRIPTION
**Pull request by prat-gpt**
# Description of change
## High level
* Set default values for buckets and token precisions in invariants through `vm.envOr`.
* Remove InvariantsTestHelpers contract.
* Shift helper methods to BaseInvariants.
* Update the `forge-std` submodule to 'v1.5.3'.
* Update invariant testing scripts.
* Add `skipTime` in merge Collateral handler.
* Add fuzzed skip time between `kick` and `take/bucketTake` in take and bucketTake handler.

### CODE REVIEW

**Review by grandizzy — APPROVED** [review]
Nice cleanup!

**Review by ith-harvey — DISMISSED** [review]
LGTM

**Review by grandizzy — APPROVED** [review]

**Review by ith-harvey — APPROVED** [review]
What we have here looks good. I'm worried about deposit take i.e. bucketTake when deposit flag is true...

Looks like we are not prepping a bucket to have deposit in it but simply performing the take regardless of the bucket's deposit amount?

I'm fine if this issue is tackled in a separate PR though.

**Comment by prat-gpt** [comment]
> What we have here looks good. I'm worried about deposit take i.e. bucketTake when deposit flag is true...
> 
> Looks like we are not prepping a bucket to have deposit in it but simply performing the take regardless of the bucket's deposit amount?
> 
> I'm fine if this issue is tackled in a separate PR though.

Will brainstorm on this and add this in a separate PR.

**Pull request merged**
