### PR TITLE
Add scaled quote token amount

### PR DESCRIPTION
**Pull request by prat-gpt**
- Round down the quote token amount to add in `addQuoteToken` method as per the quote token scale.

### CODE REVIEW

**Review by grandizzy — COMMENTED** [review]
lgtm how do you suggest to handle case when _getTokenScaledAmount returns 0, shouldn't we just revert? or actually let them spend gas on 0 transfer?

**Review by EdNoepel — APPROVED** [review]
LGTM; much thanks.

**Comment by EdNoepel** [comment]
> lgtm how do you suggest to handle case when _getTokenScaledAmount returns 0, shouldn't we just revert?

On the fence regarding this.  They can add 0 to update the interest rate.  Should they also update the interest rate if they add 0.00001 on a 4-decimal token?  Or better to give them feedback that they're probably doing something wrong and save some gas?

**Comment by grandizzy** [comment]
> > lgtm how do you suggest to handle case when _getTokenScaledAmount returns 0, shouldn't we just revert?
> 
> On the fence regarding this. They can add 0 to update the interest rate. Should they also update the interest rate if they add 0.00001 on a 4-decimal token? Or better to give them feedback that they're probably doing something wrong and save some gas?

Actually on the 2nd thought let them burn gas, I don't think a good actor could provide such amounts

**Review by grandizzy — APPROVED** [review]

**Pull request merged**
