### PR TITLE
Continuation of PR #1040 - code cleanup and comments

### PR DESCRIPTION
**Pull request by grandizzy**
- remove unused errors from Kicker and Taker actions libraries
- improve natspec with revert error on CRA

## Description

see https://github.com/ajna-finance/contracts/pull/1040#pullrequestreview-1791952981

## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [ ] Protocol contract size limits have not been exceeded.
- [ ] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [ ] Invariant tests have been manually executed as appropriate for the nature of the change.

### CODE REVIEW

**Review by prat-gpt — APPROVED** [review]
LGTM

**Review by dmitriia — APPROVED** [review]
Ok, but Pool's one looks to be still due:

https://github.com/ajna-finance/contracts/blob/3f7525ae53ed4ded3b4e0f6c3355756d523c695b/src/base/Pool.sol#L391-L402

```diff
    /**
     *  @inheritdoc IPoolKickerActions
     *  @dev    === Write state ===
     *  @dev    increment `latestBurnEpoch` counter
     *  @dev    update `reserveAuction.latestBurnEventEpoch` and burn event `timestamp` state
     *  @dev    === Reverts on ===
+    *  @dev    no reserves to claim `NoReserves()`
     *  @dev    5 days not passed `ReserveAuctionTooSoon()`
     *  @dev    unsettled liquidation `AuctionActive()`
     *  @dev    === Emit events ===
     *  @dev    - `KickReserveAuction`
     */
    function kickReserveAuction() external override nonReentrant {
```

**Comment by grandizzy** [comment]
> Ok, but Pool's one looks to be still due:
> 
> https://github.com/ajna-finance/contracts/blob/3f7525ae53ed4ded3b4e0f6c3355756d523c695b/src/base/Pool.sol#L391-L402
> 
> ```diff
>     /**
>      *  @inheritdoc IPoolKickerActions
>      *  @dev    === Write state ===
>      *  @dev    increment `latestBurnEpoch` counter
>      *  @dev    update `reserveAuction.latestBurnEventEpoch` and burn event `timestamp` state
>      *  @dev    === Reverts on ===
> +    *  @dev    no reserves to claim `NoReserves()`
>      *  @dev    5 days not passed `ReserveAuctionTooSoon()`
>      *  @dev    unsettled liquidation `AuctionActive()`
>      *  @dev    === Emit events ===
>      *  @dev    - `KickReserveAuction`
>      */
>     function kickReserveAuction() external override nonReentrant {
> ```

updated in https://github.com/ajna-finance/contracts/pull/1048/commits/39f11fe35d242f4800578c2386db928a96c6d75e

**Review by dmitriia — APPROVED** [review]

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Review by ith-harvey — APPROVED** [review]
LGTM

**Pull request merged**
