### PR TITLE
Hypothetical lup was used to calculate interest rate in `lenderKick`

### PR DESCRIPTION
**Pull request by prat-gpt**
## Description

* Updated interest rate calculation to calculate interest rate from current lup instead of hypothetical lup in `lenderKick`.

## Purpose

* Hypothetical lup was used to calculate interest rate in `lenderKick` which could lead to incorrect interest rate calculations.

## Impact

* Small increase in `lenderKick` gas cost.

## Tasks

- [X] Changes to protocol contracts are covered by unit tests executed by CI.
- [X] Protocol contract size limits have not been exceeded.
- [X] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [X] Scope labels have been assigned as appropriate.
- [X] Invariant tests have been manually executed as appropriate for the nature of the change.

### CODE REVIEW

**Review by EdNoepel — APPROVED** [review]
The cost of the extra Fenwick tree traversal seems worth having an accurate interest rate update.

**Review by ith-harvey — APPROVED** [review]
LGTM

**Review by mattcushman — APPROVED** [review]
lgtm.  

Should we have a unit test that actually checks this?  I guess if no baselines changed that we don't have a test in which a book in which the dynamics of this matter for subsequent interest computations.

**Comment by ith-harvey** [comment]
Spoke with @EdNoepel and @prateek105 consensus was no unit test is needed. We already have coverage in existing lenderKick unit tests.

**Comment by grandizzy** [comment]
a different approach (less gas / contract size and more readable code) to fix this https://github.com/ajna-finance/contracts/pull/1005/commits/8fe6acd87ef646b8ad3f61e84c664009fd7a494e

**Pull request merged**
