### PR TITLE
Correct PoolInfoUtils.momp(...) calculation

### PR DESCRIPTION
**Pull request by EdNoepel**
# Description of change
## High level
Resolve bug in `PoolInfoUtils.momp(...)`. 

# Description of bug or vulnerability and solution
 `PoolInfoUtils` was omitting the auction count when dividing pool debt by the number of loans.
Resolved by adding (new) `pool.totalAuctionsInPool()` to loan count.
Sprinkled some checks around the unit tests.

# Contract size
This isn't called from pool and did not affect core contract sizes.
## Pre Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool         -  21,781B  (88.62%)
  ERC20Pool          -  21,170B  (86.14%)
  Auctions           -  19,710B  (80.20%)
```
## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  21,781B  (88.62%)
  ERC20Pool                -  21,170B  (86.14%)
  Auctions                 -  19,710B  (80.20%)
```

# Gas usage
This is read-only call is not used in pool transactions.

### CODE REVIEW

**Review by grandizzy — APPROVED** [review]
LGTM

**Review by mattcushman — APPROVED** [review]
lgtm

**Review by dmitriia — APPROVED** [review]
Looks ok

**Comment by EdNoepel** [comment]
I did not close this.  I force pushed the branch after reapplying the change to `develop`.

**Pull request closed without merging**
