### PR TITLE
fix typo in license

### PR DESCRIPTION
**Pull request by EdNoepel**
# Description of change
## High level
Fixed typo in license section of README.

# Description of bug or vulnerability and solution
no vulnerability

# Contract size
no code change

# Gas usage
no code change

### CODE REVIEW

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Review by ith-harvey — APPROVED** [review]
LGTM

**Review by prat-gpt — APPROVED** [review]

**Comment by grandizzy** [comment]
not sure against which version of code this PR is made but doesn't look like against latest master. unit tests are also failing

**Review by grandizzy — CHANGES_REQUESTED** [review]
please issue against latest develop

**Review by grandizzy — APPROVED** [review]

**Pull request merged**
