### PR TITLE
Add Helper method for updating post draw/repay debt actions, set optmizer runs to 200

### PR DESCRIPTION
**Pull request by grandizzy**
# Description of change
## High level
* Reduce duplicated code by:
  * use same `DebtChangeResult` struct to return result of `BorrowerActions.drawDebt` and `BorrowerActions.repayDebt` (that is instead `RepayDebtResult` and `DrawDebtResult` structs). Return `quoteTokenToRepay_` var on repayDebt` in addition to struct
  * concentrate logic for update state after repay / draw debt in single `Pool._updatePostDebtChangeState` function. Used in `ERC20Pool` and `ERC721Pool` functions for `drawDebt` and `repayDebt`
* Set optimizer runs to 200 as contracts have now enough space

# Contract size
## Pre Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,350B  (99.08%)
  ERC20Pool                -  23,578B  (95.94%)
```
## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool         -  24,426B  (99.39%)
  ERC20Pool          -  23,624B  (96.12%)
```

# Gas usage
## Pre Change
```
| Function Name                        | min             | avg    | median | max     | # calls |
| addQuoteToken                        | 122500          | 179774 | 164363 | 745043  | 60004   |
| bucketTake                           | 309224          | 327865 | 327866 | 346507  | 4       |
| drawDebt                             | 253186          | 298177 | 272082 | 812414  | 136003  |
| kick                                 | 149467          | 223488 | 221980 | 1034805 | 48000   |
| kickWithDeposit                      | 199590          | 277221 | 273367 | 1000575 | 8000    |
| moveQuoteToken                       | 272093          | 272093 | 272093 | 272093  | 1       |
| removeQuoteToken                     | 146623          | 171438 | 176084 | 195785  | 4000    |
| repayDebt                            | 586918          | 614064 | 601909 | 757316  | 16002   |
| settle                               | 350544          | 350544 | 350544 | 350544  | 1       |
| take                                 | 81772           | 83349  | 83084  | 315391  | 15998   |
```
## Post Change
```
| Function Name                        | min             | avg    | median | max     | # calls |
| addQuoteToken                        | 120673          | 177845 | 162532 | 711953  | 60004   |
| bucketTake                           | 307543          | 326184 | 326184 | 344825  | 4       |
| drawDebt                             | 250710          | 295582 | 269534 | 808956  | 136003  |
| kick                                 | 148535          | 222510 | 221011 | 1033120 | 48000   |
| kickWithDeposit                      | 197510          | 275111 | 271257 | 997796  | 8000    |
| moveQuoteToken                       | 277524          | 277524 | 277524 | 277524  | 1       |
| removeQuoteToken                     | 144472          | 168273 | 172636 | 194707  | 4000    |
| repayDebt                            | 584550          | 611697 | 599542 | 754949  | 16002   |
| settle                               | 348772          | 348772 | 348772 | 348772  | 1       |
| take                                 | 80713           | 82316  | 82064  | 313356  | 15998   |
```

### CODE REVIEW

**Review by mattcushman — APPROVED** [review]
lgtm

**Review by prat-gpt — APPROVED** [review]
LGTM!

**Comment by ith-harvey** [comment]
Sorry, maybe I'm missing something. What bug is this solving for?

**Comment by grandizzy** [comment]
> Sorry, maybe I'm missing something. What bug is this solving for?

That's for solving A1 invariant violation in an uniform way

**Comment by grandizzy** [comment]
won't make the change, keeping the branch around though

**Pull request closed without merging**
