### PR TITLE
Codearena-217,256: PositionManager allows draining LP balance of other users

### PR DESCRIPTION
**Pull request by grandizzy**
# Description of change
## High level
* Reports
https://github.com/code-423n4/2023-05-ajna-findings/issues/108
https://github.com/code-423n4/2023-05-ajna-findings/issues/217
https://github.com/code-423n4/2023-05-ajna-findings/issues/256
https://github.com/code-423n4/2023-05-ajna-findings/issues/223
https://github.com/code-423n4/2023-05-ajna-findings/issues/234
https://github.com/code-423n4/2023-05-ajna-findings/issues/304
* The PositionManager contract should check if the transferred amount is equal to the lpBalance of the user in the pool contract.
* In memorialize positions function revert with `AllowanceTooLow` if allowance lower than LP balance in pool

### CODE REVIEW

**Comment by grandizzy** [comment]
converting to draft to check if fix should be implemented in Pool.transferLP rather than PositionManager

**Review by mattcushman — APPROVED** [review]
LGTM.  This should have, I believed, caused an issue with the invariant that checks that the lps recorded in position manager match those in the main contract.

**Comment by grandizzy** [comment]
> LGTM. This should have, I believed, caused an issue with the invariant that checks that the lps recorded in position manager match those in the main contract.

yep, correct, thing is that we don't have Position manager invariant finalized

**Comment by grandizzy** [comment]
> converting to draft to check if fix should be implemented in Pool.transferLP rather than PositionManager

this is a bug affecting the position manager parallel acounting of LP only, hence fixed in PositionManager

**Review by prat-gpt — APPROVED** [review]
LGTM! nice test cases added by code arena guys.

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Comment by ith-harvey** [comment]
This fix also resolved a Prototech issue as well -> https://github.com/Fixed-Point-Solutions/prototech-ajna-audit/issues/37

**Pull request merged**
