### PR TITLE
PROTOTECH-39: Pools round against themselves and in favor of borrower

### PR DESCRIPTION
**Pull request by prat-gpt**
# Description of change
## High level
* See - https://github.com/Fixed-Point-Solutions/prototech-ajna-audit/issues/39
* Add `ceilDiv` method in Maths library.
* Ceil Quote Transfer amount to favour pool balance.

### CODE REVIEW

**Review by grandizzy — CHANGES_REQUESTED** [review]
this looks good but we need to do the same rounding for ERC20 collateral

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Review by mattcushman — APPROVED** [review]
lgtm

**Comment by prat-gpt** [comment]
> this looks good but we need to do the same rounding for ERC20 collateral

Added in [94f428e](https://github.com/ajna-finance/contracts/pull/843/commits/94f428e9406e97680468dce91476c9900127c53b)

**Review by grandizzy — APPROVED** [review]
LGTM

**Review by mattcushman — APPROVED** [review]
lgtm

**Pull request merged**
