### PR TITLE
V10 queue tests and loan-linked-list queue changes

### PR DESCRIPTION
**Pull request by MikeHathaway**
This PR syncs `diez` with the latest changes in: https://github.com/ajna-finance/contracts/pull/157

- Queue tests are updated from `ERC20Pool` -> `ScaledPool`
- Added additional comments to `Queue.sol` and expand comments in tests

### CODE REVIEW

**Review by grandizzy — COMMENTED** [review]
Minor observation, there's a typo in `ScapedPoolQueue.t.sol` file name

**Comment by MikeHathaway** [comment]
> Minor observation, there's a typo in `ScapedPoolQueue.t.sol` file name

Good catch, updated accordingly.

**Review by grandizzy — APPROVED** [review]
LGTM

**Review by EdNoepel — APPROVED** [review]
Queue implementation is up-to-date.  LGTM.

**Pull request merged**
