### PR TITLE
Mul before div consistency

### PR DESCRIPTION
**Pull request by grandizzy**
# Description of change
## High level
* Consistent mul before div across contracts
  * Mul before div when calculating `_dwatp`, `t0KickPenalty` and `_lenderInterestMargin`
  * no test change for `_dwatp` and `_lenderInterestMargin` changes
  * test updates with rounding for `t0KickPenalty` update

# Description of bug or vulnerability and solution
* Solidity best practice multiply before division

### CODE REVIEW

**Review by mattcushman — APPROVED** [review]
lgtm

**Review by EdNoepel — COMMENTED** [review]
PR description missing template sections for contract size and gas change.

**Review by ith-harvey — APPROVED** [review]
How are we sure this is all of the places we perform this action? Did you just manually look through?

Noting we sqr then divide when calculating `t0Debt2ToCollateral`, is that an issue? -> https://github.com/ajna-finance/contracts/blob/develop/src/base/Pool.sol#L583

I also suggest adding to the description of this PR that this solved a rounding issue bug in invariants tests (if it did of course : )).

LGTM

**Comment by grandizzy** [comment]
> PR description missing template sections for contract size and gas change.

There should be no change in contract size / gas consumption, no logic was changed but switched same ops

**Comment by grandizzy** [comment]
> How are we sure this is all of the places we perform this action? Did you just manually look through?
Correct, I searched wdivs and reviewed. Hope I didn't miss any ..

> 
> I also suggest adding to the description of this PR that this solved a rounding issue bug in invariants tests (if it did of course : )).
> 

There's no explicit failure in invariants fir these but they could contribute to other failures

> LGTM

**Comment by grandizzy** [comment]
> How are we sure this is all of the places we perform this action? Did you just manually look through?
> 
> Noting we sqr then divide when calculating `t0Debt2ToCollateral`, is that an issue? -> https://github.com/ajna-finance/contracts/blob/develop/src/base/Pool.sol#L583

That's fine, it's basically a mul (sqr) then divide

> 
> I also suggest adding to the description of this PR that this solved a rounding issue bug in invariants tests (if it did of course : )).
> 
> LGTM

**Pull request merged**
