### PR TITLE
Invariants improvements: Add stamp Loan handler

### PR DESCRIPTION
**Pull request by prat-gpt**
# Description of change
## High level
* Add stamp Loan handler in invariants.

### CODE REVIEW

**Comment by ith-harvey** [comment]
Would you mind explaining why this change is helpful / needed in your PR description?

**Comment by grandizzy** [comment]
> Would you mind explaining why this change is helpful / needed in your PR description?

this borrower function is not tested at all in invariants

**Review by grandizzy — APPROVED** [review]

**Review by ith-harvey — APPROVED** [review]
`stampLoan` was not called in invariants... we forgot about it. Looks good.

**Review by MikeHathaway — APPROVED** [review]
LGTM - are there any `stampLoan` specific invariants we should also be testing?

**Comment by grandizzy** [comment]
> LGTM - are there any `stampLoan` specific invariants we should also be testing?

hm, not that I'm aware of, @prateek105 any thoughts?

**Comment by prat-gpt** [comment]
> > LGTM - are there any `stampLoan` specific invariants we should also be testing?
> 
> hm, not that I'm aware of, @prateek105 any thoughts?

I am also unable to think of any @MikeHathaway @grandizzy

**Pull request merged**
