### PR TITLE
Update OZ lib to 4.8.2

### PR DESCRIPTION
**Pull request by grandizzy**
# Contract size
```
## Pre Change
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,356B  (99.10%)
  ERC20Pool                -  23,802B  (96.85%)
  Auctions                 -  21,067B  (85.72%)
```

## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,356B  (99.10%)
  ERC20Pool                -  23,802B  (96.85%)
  Auctions                 -  21,125B  (85.95%)
```

# Gas usage
## Pre Change
```
| Function Name                        | min             | avg    | median | max    | # calls |
| addQuoteToken                        | 119315          | 175668 | 161115 | 694632 | 60004   |
| bucketTake                           | 327628          | 348558 | 348570 | 369464 | 4       |
| drawDebt                             | 248277          | 292957 | 268224 | 785846 | 136003  |
| kick                                 | 195615          | 221635 | 220800 | 986346 | 48000   |
| kickWithDeposit                      | 240830          | 275372 | 270174 | 983400 | 8000    |
| moveQuoteToken                       | 266942          | 266942 | 266942 | 266942 | 1       |
| removeQuoteToken                     | 133868          | 155338 | 158301 | 180802 | 4000    |
| repayDebt                            | 556944          | 589087 | 578983 | 737254 | 16002   |
| settle                               | 212455          | 212455 | 212455 | 212455 | 1       |
| take                                 | 97715           | 102846 | 102502 | 315779 | 15998   |
```

## Post Change
```
| Function Name                        | min             | avg    | median | max    | # calls |
| addQuoteToken                        | 119315          | 175668 | 161115 | 694632 | 60004   |
| bucketTake                           | 327628          | 348558 | 348570 | 369464 | 4       |
| drawDebt                             | 248277          | 292957 | 268224 | 785846 | 136003  |
| kick                                 | 195615          | 221635 | 220800 | 986346 | 48000   |
| kickWithDeposit                      | 240830          | 275372 | 270174 | 983400 | 8000    |
| moveQuoteToken                       | 266942          | 266942 | 266942 | 266942 | 1       |
| removeQuoteToken                     | 133868          | 155338 | 158301 | 180802 | 4000    |
| repayDebt                            | 556944          | 589087 | 578983 | 737254 | 16002   |
| settle                               | 212420          | 212420 | 212420 | 212420 | 1       |
| take                                 | 97715           | 102846 | 102502 | 315779 | 15998   |
```

### CODE REVIEW

**Review by EdNoepel — COMMENTED** [review]
Missing PR template.  Useful to see how the library change impacts contract size and gas consumption.

**Comment by grandizzy** [comment]
> Missing PR template. Useful to see how the library change impacts contract size and gas consumption.

makes sense, updated

**Review by prat-gpt — APPROVED** [review]
LGTM. There are gas [optimizations](https://blog.openzeppelin.com/announcing-openzeppelin-contracts-4-8/) in ERC20Votes which is inherited in Ajna token contract on ecosystem coordination repo. If we are going to redeploy Ajna token this upgrade should be made on ecosystem repo as well. @MikeHathaway

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
