### PR TITLE
Remove radius from Queue

### PR DESCRIPTION
**Pull request by ith-harvey**
To reduce complexity for future development / testing as well as come up with a better solution, removed radius from queue implementation.
* Removed `_searchRadius()` method
* Removed `radius` arg from following methods : `addCollateral`, `_updateLoanQueue`, `borrow`, `removeCollateral`, `repay`
* Updated corresponding tests

### CODE REVIEW

**Review by EdNoepel — APPROVED** [review]
LGTM

**Review by grandizzy — COMMENTED** [review]
LGTM, need to fix failing forge tests

**Review by grandizzy — CHANGES_REQUESTED** [review]
There's an issue with how `thresholdPrice` is calculated in PR as it removes using `_threshold_price` function and instead that is now done inline, e.g. here
https://github.com/ajna-finance/contracts/pull/175/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081L220

however meanwhile the `_threshold_price` function was updated to `Maths.wdiv(debt_, Maths.wmul(inflator_, collateral_))` while in PR inline is still `Maths.wdiv(borrower.debt, borrower.collateral)`

I created a PR here https://github.com/ajna-finance/contracts/pull/179 and would like to use that one if agree

**Comment by EdNoepel** [comment]
> There's an issue with how `thresholdPrice` is calculated in PR as it removes using `_threshold_price` function and instead that is now done inline, e.g. here https://github.com/ajna-finance/contracts/pull/175/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081L220
> 
> however meanwhile the `_threshold_price` function was updated to `Maths.wdiv(debt_, Maths.wmul(inflator_, collateral_))` while in PR inline is still `Maths.wdiv(borrower.debt, borrower.collateral)`
> 
> I created a PR here #179 and would like to use that one if agree

That second formula is also wrong; the correct formula is in PR #178:
https://github.com/ajna-finance/contracts/pull/178/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081R559

Happy to merge #179 and then #178 if that's easier.

**Comment by grandizzy** [comment]
> > There's an issue with how `thresholdPrice` is calculated in PR as it removes using `_threshold_price` function and instead that is now done inline, e.g. here https://github.com/ajna-finance/contracts/pull/175/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081L220
> > however meanwhile the `_threshold_price` function was updated to `Maths.wdiv(debt_, Maths.wmul(inflator_, collateral_))` while in PR inline is still `Maths.wdiv(borrower.debt, borrower.collateral)`
> > I created a PR here #179 and would like to use that one if agree
> 
> That second formula is also wrong; the correct formula is in PR #178: https://github.com/ajna-finance/contracts/pull/178/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081R559

> > There's an issue with how `thresholdPrice` is calculated in PR as it removes using `_threshold_price` function and instead that is now done inline, e.g. here https://github.com/ajna-finance/contracts/pull/175/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081L220
> > however meanwhile the `_threshold_price` function was updated to `Maths.wdiv(debt_, Maths.wmul(inflator_, collateral_))` while in PR inline is still `Maths.wdiv(borrower.debt, borrower.collateral)`
> > I created a PR here #179 and would like to use that one if agree
> 
> That second formula is also wrong; the correct formula is in PR #178: https://github.com/ajna-finance/contracts/pull/178/files#diff-176d8df3790b493909cf7dfeaab5f53f0ff7a06ef58f6f194406399584105081R559
> 
> Happy to merge #179 and then #178 if that's easier.

Yeah, that makes sense, going to merge PR #179 and review #178

**Review by EdNoepel — CHANGES_REQUESTED** [review]
Revoking my approval due to changes made after my review.

**Comment by grandizzy** [comment]
addressed in PR #179

**Pull request closed without merging**
