### PR TITLE
Modify computation of quotetoken amount in TakerActions.sol

### PR DESCRIPTION
**Pull request by mattcushman**
to compute bond reward accurately for collateral constrained
takes with collateral tokens with decimals != 18.

## Description

Fix how quote token and therefore bond quantities are computed to be more accurate in case of debt constrained takes.  This makes the bucket exchange rates more stable in the case of `bucketTake`s.
## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [ ] Protocol contract size limits have not been exceeded.
- [ ] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [ ] Invariant tests have been manually executed as appropriate for the nature of the change.

### CODE REVIEW

**Review by EdNoepel — APPROVED** [review]
Initially I was skeptical, but this comment from chat explained it:
> Basically, the bond reward was being computed off the constraint imposed by the debt, but the actual quote token getting decremented from the bucket was based on the rounded collateral amount.  now they are both using the rounded collateral amount.

LGTM.

**Review by grandizzy — APPROVED** [review]

**Review by ith-harvey — APPROVED** [review]
LGTM

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Review by prat-gpt — APPROVED** [review]
LGTM

**Review by dmitriia — COMMENTED** [review]
Looks ok

**Pull request merged**
