### PR TITLE
Deployment updates

### PR DESCRIPTION
**Pull request by EdNoepel**
# Description of change
## High level
Do not deploy `RewardsManager`, which is meant to be a reference implementation.
Deploy new `PoolInfoUtilsMulticall` contract, intended for use by subgraph.

# Description of bug or vulnerability and solution
no bug/vulnerability

# Contract size
no contract changes

# Gas usage
no contract changes

### CODE REVIEW

**Comment by EdNoepel** [comment]
Intentionally made this PR against `master` because changes need to be in place for the current release.

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Review by prat-gpt — APPROVED** [review]
lgtm.

**Review by ith-harvey — APPROVED** [review]
LGTM

**Pull request merged**
