### PR TITLE
Add sdk setup script and readme

### PR DESCRIPTION
**Pull request by grandizzy**

### CODE REVIEW

**Review by EdNoepel — COMMENTED** [review]
Mainnet addresses are used throughout these changes, yet no mention of the network affinity is made.  I'd be happy to extend this to make `sdk_setup.py` chain agnostic, moving all addresses into the JSON.

**Comment by grandizzy** [comment]
> Mainnet addresses are used throughout these changes, yet no mention of the network affinity is made. I'd be happy to extend this to make `sdk_setup.py` chain agnostic, moving all addresses into the JSON.

Ah, good point, yeah, let me add such

**Comment by grandizzy** [comment]
> > Mainnet addresses are used throughout these changes, yet no mention of the network affinity is made. I'd be happy to extend this to make `sdk_setup.py` chain agnostic, moving all addresses into the JSON.
> 
> Ah, good point, yeah, let me add such

@EdNoepel here it is https://github.com/ajna-finance/contracts/pull/299/commits/c9f2a53f508c02417f17710eae2cac3e23e03569
and https://github.com/ajna-finance/contracts/pull/299/commits/7fe45b077bfa3bd681de570b363466499bff4a94 for fixing MKR address and properly naming `BAYC`

**Review by EdNoepel — APPROVED** [review]
LGTM

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
