### PR TITLE
Code4rena improvements: style and gas

### PR DESCRIPTION
**Pull request by grandizzy**
Style:
- [N‑01] The nonReentrant modifier should occur before all other modifiers
- [N‑02] require()/revert() statements should have descriptive reason strings
- [N‑11] Lines are too long
- [N‑12] Typos 

Gas optimization:
- [G-01] | Missing zero-address check in constructor
- [G‑04] Multiple accesses of a mapping/array should use a local variable cache
- [G-05] Do not calculate constants variables

Gas pre change:
```
| src/PositionManager.sol:PositionManager contract |                 |        |        |         |         |
|--------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                  | Deployment Size |        |        |         |         |
| 3922538                                          | 19868           |        |        |         |         |
| Function Name                                    | min             | avg    | median | max     | # calls |
| tokenURI                                         | 2490            | 466347 | 466347 | 930205  | 2       |

| src/RewardsManager.sol:RewardsManager contract |                 |         |         |         |         |
|------------------------------------------------|-----------------|---------|---------|---------|---------|
| Deployment Cost                                | Deployment Size |         |         |         |         |
| 1953583                                        | 10053           |         |         |         |         |
| Function Name                                  | min             | avg     | median  | max     | # calls |
| calculateRewards                               | 33708           | 49889   | 38027   | 163831  | 71      |
| claimRewards                                   | 523             | 98854   | 104460  | 393064  | 74      |
| getBucketStateStakeInfo                        | 660             | 2658    | 2660    | 2660    | 81279   |
| getStakeInfo                                   | 694             | 694     | 694     | 694     | 96      |
| moveStakedLiquidity                            | 1828645         | 1971949 | 1971949 | 2115253 | 2       |
| stake                                          | 118764          | 412729  | 474773  | 892271  | 28      |
| unstake                                        | 78573           | 176225  | 141226  | 398616  | 13      |
| updateBucketExchangeRatesAndClaim              | 9614            | 238486  | 176062  | 537409  | 44      |
```
Gas post change:
```
| src/PositionManager.sol:PositionManager contract |                 |        |        |         |         |
|--------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                  | Deployment Size |        |        |         |         |
| 3926938                                          | 19890           |        |        |         |         |
| Function Name                                    | min             | avg    | median | max     | # calls |
| tokenURI                                         | 2535            | 466370 | 466370 | 930205  | 2       |

| src/RewardsManager.sol:RewardsManager contract |                 |         |         |         |         |
|------------------------------------------------|-----------------|---------|---------|---------|---------|
| Deployment Cost                                | Deployment Size |         |         |         |         |
| 1954583                                        | 10058           |         |         |         |         |
| Function Name                                  | min             | avg     | median  | max     | # calls |
| calculateRewards                               | 33710           | 60678   | 38029   | 163736  | 36      |
| claimRewards                                   | 523             | 101380  | 104139  | 392944  | 39      |
| getBucketStateStakeInfo                        | 660             | 2658    | 2660    | 2660    | 81279   |
| getStakeInfo                                   | 694             | 694     | 694     | 694     | 74      |
| moveStakedLiquidity                            | 1828629         | 1971931 | 1971931 | 2115234 | 2       |
| stake                                          | 118769          | 339455  | 309081  | 892224  | 41      |
| unstake                                        | 78560           | 176217  | 141209  | 398596  | 13      |
| updateBucketExchangeRatesAndClaim              | 9604            | 294667  | 286688  | 537384  | 24      |
```

### CODE REVIEW

**Comment by ith-harvey** [comment]
I'm OK with the changes, seem trivial. However, it seems the average gas went up? Why would we include these changes if it makes the average gas call go up?

**Comment by grandizzy** [comment]
> I'm OK with the changes, seem trivial. However, it seems the average gas went up? Why would we include these changes if it makes the average gas call go up?

these are fuzzed tests where hard to compare, worth double checking on a single call

**Review by mattcushman — APPROVED** [review]
lgtm

**Review by MikeHathaway — DISMISSED** [review]
LGTM. Looks like there's some merge conflicts, but these changes all make sense

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
