### PR TITLE
Kirill [M-07] | Prevent reserves auction kick until all pending auctions are fully settled

### PR DESCRIPTION
**Pull request by grandizzy**
## Description

Implement suggested resolution for `[M-07] | Liquidation of positions with bad debt can cause losses for `HPB` depositors`

## Purpose

- Don’t allow calls to `kickReserveAuction` until all pending auctions are fully settled - revert with `AuctionNotCleared` if so
- update unit test to cover scenario
- apply consistent style for `_revertIfAuctionPriceBelow` helper (storage param first)

## Impact

Slightly decrease in contracts size
```
| ERC20Pool                     | 23.637    | 0.939       |
| ERC721Pool                    | 24.372    | 0.204       |
```
vs develop
```
| ERC20Pool                     | 23.599    | 0.977       |
| ERC721Pool                    | 24.334    | 0.242       |
```

## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [x] Protocol contract size limits have not been exceeded.
- [ ] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [ ] Scope labels have been assigned as appropriate.
- [ ] Invariant tests have been manually executed as appropriate for the nature of the change.

### CODE REVIEW

**Review by dmitriia — APPROVED** [review]
Looks ok

**Review by k1rill-fedoseev — APPROVED** [review]
LGTM

**Review by EdNoepel — COMMENTED** [review]
Reusing `AuctionNotCleared` error seems misleading; `AuctionActive` seems more accurate.

**Comment by grandizzy** [comment]
> Reusing `AuctionNotCleared` error seems misleading; `AuctionActive` seems more accurate.

makes sense

**Pull request merged**
