### PR TITLE
Optimize stake cost by reducing calls to currentBurnEpoch

### PR DESCRIPTION
**Pull request by brianmcmichael**
# Description of change
## High level
* Optimization/Code reduction in staking
  * Optimization to staking cost by avoiding duplicate external calls to `pool.currentBurnEpoch`
  * Minor other optimizations to storage location calls and cast locations

# Description of bug or vulnerability and solution
* External call duplication
  * Internal helper function is calling for current burn epoch when it's available in parent function. This allows re-use of the data, avoiding an external call in stake and reducing cost.
  * Nested helper functions obfuscate code and call re-use. Evaluate whether other calls can be de-duplicated.

# Contract size
## Pre Change
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1705662                                        | 8934            |        |        |         |         |
## Post Change
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1710462                                        | 8958            |        |        |         |         |

# Gas usage
## Pre Change
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1705662                                        | 8934            |        |        |         |         |
| Function Name                                  | min             | avg    | median | max     | # calls |
| calculateRewards                               | 30268           | 77190  | 56918  | 167802  | 29      |
| claimRewards                                   | 721             | 209680 | 128083 | 557789  | 37      |
| emergencyUnstake                               | 25225           | 39064  | 27596  | 97196   | 18      |
| getBucketStateStakeInfo                        | 904             | 4651   | 4904   | 4904    | 236449  |
| getStakeInfo                                   | 748             | 748    | 748    | 748     | 102     |
| isBucketUpdated                                | 720             | 720    | 720    | 720     | 246     |
| stake                                          | 157144          | 639072 | 617116 | 1192609 | 61      |
| unstake                                        | 564             | 195052 | 131531 | 587066  | 23      |
| updateBucketExchangeRatesAndClaim              | 4408            | 282845 | 274092 | 574085  | 44      |
## Post Change
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1708662                                        | 8949            |        |        |         |         |
| Function Name                                  | min             | avg    | median | max     | # calls |
| calculateRewards                               | 30268           | 50520  | 38228  | 167802  | 148     |
| claimRewards                                   | 721             | 147474 | 120100 | 556596  | 156     |
| emergencyUnstake                               | 26223           | 40995  | 28594  | 103794  | 18      |
| getBucketStateStakeInfo                        | 904             | 4651   | 4904   | 4904    | 236449  |
| getStakeInfo                                   | 748             | 748    | 748    | 748     | 236     |
| isBucketUpdated                                | 720             | 720    | 720    | 720     | 246     |
| stake                                          | 156168          | 554615 | 613400 | 1151324 | 76      |
| unstake                                        | 564             | 194124 | 130592 | 585893  | 23      |
| updateBucketExchangeRatesAndClaim              | 4408            | 260778 | 187166 | 557618  | 53      |

### CODE REVIEW

**Review by prat-gpt — APPROVED** [review]
LGTM

**Review by EdNoepel — APPROVED** [review]
LGTM; need to resolve conflict though.

**Review by ith-harvey — APPROVED** [review]
LGTM

**Review by MikeHathaway — APPROVED** [review]
LGTM. Thanks for the improvement

**Pull request merged**
