### PR TITLE
Expand code coverage

### PR DESCRIPTION
**Pull request by MikeHathaway**
## Description

- Add full coverage of `PermitERC20` and `PoolInfoUtils`

## Tasks

- [ ] Changes to protocol contracts are covered by unit tests executed by CI.
- [ ] Protocol contract size limits have not been exceeded.
- [ ] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [ ] Scope labels have been assigned as appropriate.
- [ ] Invariant tests have been manually executed as appropriate for the nature of the change.

### CODE REVIEW

**Review by EdNoepel — COMMENTED** [review]
I am working on a PR off this which creates a liquidation within this test for checking the numbers.

**Review by EdNoepel — APPROVED** [review]
LGTM

**Review by prat-gpt — APPROVED** [review]
LGTM. Can cherry pick https://github.com/ajna-finance/contracts/pull/1010/commits/83072b109a45e887f544458df80ef458ea907394 commit to fix failing unit tests due to new foundry version

**Comment by EdNoepel** [comment]
> LGTM. Can cherry pick [83072b1](https://github.com/ajna-finance/contracts/commit/83072b109a45e887f544458df80ef458ea907394) commit to fix failing unit tests due to new foundry version

Because the target branch was already merged, I created a new merge branch https://github.com/ajna-finance/contracts/tree/code-cov-exp-develop to get this into develop.  PR would look nasty however, because it would double up on all prior `merge-rc9` commits, and touch `src/`.  Another option would be to merge this to `merge-rc9` and then merge `merge-rc9` into `develop` again.  @ith-harvey

**Comment by MikeHathaway** [comment]
> > LGTM. Can cherry pick [83072b1](https://github.com/ajna-finance/contracts/commit/83072b109a45e887f544458df80ef458ea907394) commit to fix failing unit tests due to new foundry version
> 
> Because the target branch was already merged, I created a new merge branch https://github.com/ajna-finance/contracts/tree/code-cov-exp-develop to get this into develop. PR would look nasty however, because it would double up on all prior `merge-rc9` commits, and touch `src/`. Another option would be to merge this to `merge-rc9` and then merge `merge-rc9` into `develop` again. @ith-harvey

Resolved conflicts, but this PR should be squashed

**Review by ith-harvey — APPROVED** [review]
LGTM

**Pull request merged**
