### PR TITLE
chore: Consolidate contracts to reduce inheritance

### PR DESCRIPTION
**Pull request by lucas-manuel**
Was able to remove 18 files from the repo by consolidating inheritance.

Initial inheritance structure:

Screen Shot 2022-07-01 at 2 00 18 PM

New inheritance structure

Screen Shot 2022-07-01 at 2 10 15 PM

### CODE REVIEW

**Review by MikeHathaway — APPROVED** [review]
LGTM! It might be a good idea to move `ERC20Pool`, `ERC721Pool`, and the associated factories to the top level of the src directory as well.

**Comment by lucas-manuel** [comment]
Totally agree, thought we could reorg the directory structure as well - should do in a new PR though imo

**Review by grandizzy — APPROVED** [review]
Nice, this should also help when moving to fenwick tree as code will be better traceable

**Review by EdNoepel — APPROVED** [review]
LGTM

**Pull request merged**
