### PR TITLE
Revert - Increment nonce on approve to avoid signature replay (#906)

### PR DESCRIPTION
**Pull request by prat-gpt**
# Description of change
## High level
* See - https://github.com/sherlock-audit/2023-04-ajna-judging/issues/46
* Reverts PR #906

### CODE REVIEW

**Review by grandizzy — APPROVED** [review]
LGTM :ok_hand:

**Review by EdNoepel — COMMENTED** [review]
Why are we reverting this change?

**Review by dmitriia — APPROVED** [review]
Looks ok

**Review by EdNoepel — APPROVED** [review]
Found the discord thread.  LGTM.

**Comment by MikeHathaway** [comment]
> Why are we reverting this change?

Per the discussion in sherlock channel: "I checked the reasoning, after reading the discussion thread https://ethereum-magicians.org/t/eip-4494-extending-erc-2612-style-permits-to-erc-721-nfts/7519#h-1-owner-based-or-tokenid-based-nonces-1   on this EIP it looks invalid now to me. This thread mentions that One gain from this pattern is that allows an owner to create multiple permits for the same NFT, since the nonce will only be incremented if the NFT is transferred. which implies that multiple approvals for same tokenId is a required behaviour."

We are reverting back to the standard ERC-4494 implementation

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Review by ith-harvey — APPROVED** [review]

**Pull request merged**
