### PR TITLE
Consistent naming, replace lpTokens with LPs

### PR DESCRIPTION
**Pull request by grandizzy**
- rename TransferLPTokens event to TransferLPs
- rename PositionManager.getLPTokens to PositionManager.getLPs
- rename tests, update comments

### CODE REVIEW

**Review by ith-harvey — CHANGES_REQUESTED** [review]
I suggest we update all instances of `_lpTokenAllowances` to `_lpAllowances` in `pool.sol` as well.

**Comment by grandizzy** [comment]
> I suggest we update all instances of `_lpTokenAllowances` to `_lpAllowances` in `pool.sol` as well.

Good catch

**Comment by grandizzy** [comment]
> `_lpAllowances`

changed with https://github.com/ajna-finance/contracts/pull/543/commits/42892c4eb7d51c82d0839c28fa905bcddc4cac47

**Review by dmitriia — COMMENTED** [review]
Ok

**Pull request merged**
