### PR TITLE
Sherlock 111: Adversary can grief kicker by frontrunning kick with a large amount of loan

### PR DESCRIPTION
**Pull request by grandizzy**
- fix for #619 (Sherlock https://github.com/sherlock-audit/2023-01-ajna-judging/issues/111)
- add `limitIndex_` param to `kick` and `kickWithDeposit` functions (Lower bound of `NP` tolerated when kicking the auction.)
- renamed `_revertIfLupDroppedBelowLimit` to a more general `_revertIfPriceDroppedBelowLimit` and used it to check if `NP` below specified limit when auction kicked
- added `KickLocalVars` struct for local vars in `Auction._kick` function in order to prevent stack too deep error
- updated tests, added revert test when limit is specified as index 0

### CODE REVIEW

**Review by mattcushman — APPROVED** [review]
lgtm

**Review by EdNoepel — APPROVED** [review]
I like that we're reusing the revert helper, and that the UX is somewhat consistent with borrower operations, which have a LUP-based limit.

**Review by dmitriia — COMMENTED** [review]
Looks ok.

Ideally I would rename

`@param  limitIndex_      Lower bound of NP tolerated when kicking the auction`

to something like

`@param  limitIndex_      Index of the lower bound of NP tolerated when kicking the auction`

Also, forrmally it should be 

https://github.com/ajna-finance/contracts/blob/b00e3e51d04acf7ef5bde168c6871a486b4e75a3/src/libraries/external/Auctions.sol#L847

```solidity
-       // check if NP is still greater than the price limit provided by the kicker - done to prevent frontrunning kick auction call with a large amount of loan
+       // check if NP is not less than price at the limit index provided by the kicker - done to prevent frontrunning kick auction call with a large amount of loan
```

**Comment by grandizzy** [comment]
> Looks ok.
> 
> Ideally I would rename
> 
> `@param limitIndex_ Lower bound of NP tolerated when kicking the auction`
> 
> to something like
> 
> `@param limitIndex_ Index of the lower bound of NP tolerated when kicking the auction`
> 
> Also, forrmally it should be
> 
> https://github.com/ajna-finance/contracts/blob/b00e3e51d04acf7ef5bde168c6871a486b4e75a3/src/libraries/external/Auctions.sol#L847
> 
> ```solidity
> -       // check if NP is still greater than the price limit provided by the kicker - done to prevent frontrunning kick auction call with a large amount of loan
> +       // check if NP is not less than price at the limit index provided by the kicker - done to prevent frontrunning kick auction call with a large amount of loan
> ```

updated comments in https://github.com/ajna-finance/contracts/pull/664

**Pull request merged**
