### PR TITLE
Keep ERC20 collateral scale and NFT subset as immutable

### PR DESCRIPTION
**Pull request by grandizzy**
- lower gas (no read from storage but from calldata https://github.com/wighawag/clones-with-immutable-args#cloneswithimmutableargs) and lower contract size

```
| Function Name                              | min             | avg    | median | max    | # calls |
| addQuoteToken                              | 100988          | 160112 | 143603 | 718127 | 56003   |
| bucketTake                                 | 345679          | 410809 | 410826 | 475907 | 4       |
| collateralScale                            | 430             | 430    | 430    | 430    | 1       |
| drawDebt                                   | 198742          | 245430 | 219225 | 742650 | 128003  |
| kick                                       | 150123          | 174863 | 173572 | 997349 | 48000   |
| moveQuoteToken                             | 282882          | 282882 | 282882 | 282882 | 1       |
| quoteTokenScale                            | 410             | 410    | 410    | 410    | 8002    |
| removeQuoteToken                           | 144711          | 177802 | 177715 | 198282 | 4000    |
| repayDebt                                  | 525764          | 557699 | 546999 | 705568 | 16002   |
| take                                       | 49213           | 49839  | 49632  | 335744 | 15998   |


| Function Name                              | min             | avg    | median | max    | # calls |
| addQuoteToken                              | 100988          | 160110 | 143603 | 658072 | 56003   |
| bucketTake                                 | 345679          | 410809 | 410826 | 475907 | 4       |
| collateralScale                            | 2469            | 2469   | 2469   | 2469   | 1       |
| drawDebt                                   | 198787          | 245473 | 219270 | 742650 | 128003  |
| kick                                       | 150123          | 174863 | 173572 | 997349 | 48000   |
| moveQuoteToken                             | 283352          | 283352 | 283352 | 283352 | 1       |
| quoteTokenScale                            | 410             | 410    | 410    | 410    | 8002    |
| removeQuoteToken                           | 158671          | 177811 | 177715 | 201433 | 4000    |
| repayDebt                                  | 525764          | 557700 | 546999 | 705568 | 16002   |
| take                                       | 49238           | 49864  | 49656  | 337369 | 15998   |
```

### CODE REVIEW

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Review by EdNoepel — COMMENTED** [review]
I don't understand this change.  Don't we need `collateralScale` to differ in pools with collaterals that have a different number of decimal places?

**Comment by grandizzy** [comment]
> I don't understand this change. Don't we need `collateralScale` to differ in pools with collaterals that have a different number of decimal places?

Yep, we need, but instead keeping it as a state var we store it as immutable arg (similar with the way we keep scale for quote token and addresses for collateral, quote token and ajna)

**Review by EdNoepel — APPROVED** [review]
LGTM

**Pull request merged**
