### PR TITLE
PROTOTECH-23,Codarena-306: Update solc to 0.8.18

### PR DESCRIPTION
**Pull request by grandizzy**
# Description of change
## High level
* See
https://github.com/Fixed-Point-Solutions/prototech-ajna-audit/issues/23
https://github.com/code-423n4/2023-05-ajna-findings/issues/306

### CODE REVIEW

**Review by MikeHathaway — COMMENTED** [review]
Should we look at 0.8.20 as well? A bunch of improvements in there. https://blog.soliditylang.org/2023/05/10/solidity-0.8.20-release-announcement/

**Comment by grandizzy** [comment]
> Should we look at 0.8.20 as well? A bunch of improvements in there. https://blog.soliditylang.org/2023/05/10/solidity-0.8.20-release-announcement/

0.8.18 was recommended by both Prototech and Codearena, plus is the one suggested by slither too afaik so I'd lock on this version...

**Review by prat-gpt — APPROVED** [review]
LGTM!

**Review by MikeHathaway — APPROVED** [review]
LGTM

**Pull request merged**
